// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ejhuzzliywibczdtadjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaHV6emxpeXdpYmN6ZHRhZGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTI2MTAsImV4cCI6MjA3ODE4ODYxMH0.LjB6P4e6U96hMGeJK3i9wQQmai_c-u0lL07xk3-9jAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);